name: MustardSeedSoftware
favicon: null
layout_spectrum: 0.720526211662218
typography_spectrum: 0.1481904669199139
title: 'Mustard Seed Software, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a662b'
    - '#000000'
    - '#9eb395'
    - '#cad5c3'
  brandStrength: 1
  lightness: 0.37105323281139135
  saturation: 1
  rhythmicContrast: 0
purpose: []
